### ISSUE TITLE
[Spec] Should PFS provide suitable partners to connect to for new nodes

### ISSUE THREAD

**Issue by palango** [raiden-network/raiden-pathfinding-service#4]
An open question is how new nodes in a token network find suitable partners. 

One idea is to use the PFS to return the a list of suitable partners, possible configurable with the desired deposit and the desired number of channels.

**Comment by devium** [comment]
I don't think this should be part of the PFS. Rather there should be something like a rudimentary order book for opening channels. Not enforceable orders but something like:
* A broadcasts "looking for a channel with a counter deposit of at least 1000 Rei, will deposit 500 Rei"
* Interested nodes answer "yup, check me out" (what and how many channels you accept could be configurable in the client, with conservative defaults)
* A picks his favorites using some simple metrics (e.g. node with highest sum of deposits or similar)

This should be in the client rather than the PFS. There's already logic for selecting partners in Raiden, just that it's very rudimentary.

**Comment by LefterisJP** [comment]
Yes I would also second Georg on that. 

If we want to improve the bootstrapping of a token network or the partner discovery in joining a token network this should happen in the [Raiden Connection Manager](https://github.com/raiden-network/raiden/blob/master/raiden/connection_manager.py)

**Comment by palango** [comment]
I agree that we don't want a service for that in the long term, but it might be a simple solution until we have to time to work out something proper.

**Comment by palango** [comment]
Closing as sentiment is against incorporating this now. We can reopen if this becomes an issue again.
